/**
 * Comment Formatter
 * Formats review results into GitHub comment format
 */

class CommentFormatter {
  /**
   * Format summary comment for PR
   */
  formatSummary(reviewResults) {
    const { summary, byFile, issues } = reviewResults;
    const errorEmoji = summary.errors > 0 ? '❌' : '✅';

    let comment = `## ${errorEmoji} Automated Code Review

### Summary
- **Total Issues**: ${summary.total}
- **Errors**: ${summary.errors}
- **Warnings**: ${summary.warnings}
- **Info**: ${summary.info}
- **Files Reviewed**: ${summary.fileCount}
- **Files with Issues**: ${summary.filesWithIssues}

`;

    if (summary.total === 0) {
      comment += `### ✨ Great job! No issues found.\n\n`;
    } else {
      comment += `### Issues by File\n\n`;

      for (const [file, fileIssues] of Object.entries(byFile)) {
        if (fileIssues.length > 0) {
          comment += `#### 📄 \`${file}\` (${fileIssues.length} issue${fileIssues.length > 1 ? 's' : ''})\n\n`;
          
          for (const issue of fileIssues) {
            const emoji = {
              error: '❌',
              warning: '⚠️',
              info: 'ℹ️'
            }[issue.severity] || '💬';

            comment += `${emoji} **Line ${issue.line}**: ${issue.rule}\n`;
            comment += `> ${issue.message}\n`;
            comment += `> 💡 ${issue.suggestion}\n\n`;
          }
        }
      }
    }

    comment += `---\n*Generated by [PR Review Agent](https://github.com/yourusername/pr-review-agent)*`;

    return comment;
  }

  /**
   * Format inline comment
   */
  formatInline(issue) {
    const emoji = {
      error: '❌',
      warning: '⚠️',
      info: 'ℹ️'
    }[issue.severity] || '💬';

    return `${emoji} **${issue.rule}** (${issue.severity})\n${issue.message}\n\n💡 *Suggestion:* ${issue.suggestion}`;
  }
}

module.exports = CommentFormatter;
